import { useState } from "react";
import { Bell, Search, Send, SlidersHorizontal } from "lucide-react";
import "./PulseReference3D.css";

export function PulseReference3DDark() {
  const [query, setQuery] = useState("");
  const [answer, setAnswer] = useState("");
  const [profile, setProfile] = useState(false);
  const [period, setPeriod] = useState("YTD");
  const ask = () => { if (query.trim()) setAnswer("Pulse identifies Assets as the priority: QAR 214M below forecast, with occupancy and leasing as the evidence-backed drivers."); };
  return <div className="pulse-ref3d dark"><div className="ref-window">
    <header className="ref-top"><div className="ref-logo"><img src="/__mockup/images/pulse-ai-official.png" alt="Pulse.ai"/></div><nav className="ref-nav">{["Overview","Businesses","Performance","Forecast","Insights","Attention","Reports"].map((item,i)=><button className={i===0?"active":""} key={item}>{item}</button>)}</nav><div className="ref-actions"><button className="round-btn" aria-label="Notifications"><Bell size={14}/></button><button className="ref-avatar" onClick={()=>setProfile(!profile)} aria-label="Open account">JJ</button></div></header>
    {profile&&<div className="profile-pop"><strong>Mr. Jasim</strong><span>President · Secure executive access</span><button onClick={()=>setProfile(false)}>Profile &amp; preferences</button><button onClick={()=>setProfile(false)}>Close account menu</button></div>}
    <main className="ref-body"><div className="ref-heading"><div><h1>Overview</h1><p>Enterprise command center · Tuesday, 18 June 2024 · Consolidated view</p></div><div className="ref-controls">{["MTD","QTD","YTD"].map(item=><button className={`ref-control ${period===item?"primary":""}`} onClick={()=>setPeriod(item)} key={item}>{item}</button>)}<button className="ref-control">01 Jan – 31 Jul⌄</button><button className="ref-control"><SlidersHorizontal size={11}/> Add widget +</button></div></div>
      <div className="ref-layout"><section className="ref-card"><div className="card-head"><h2>Enterprise revenue</h2><button className="more">···</button></div><div className="pulse-chart"><div className="chart-grid"><i/><i/><i/><i/><i/></div><div className="bars">{[64,57,73,48,40,35,46,58,52,69,62,78].map((h,i)=><button className="bar" key={i} style={{height:`${h}%`}} aria-label={`Period ${i+1}`}/>)}</div><div className="chart-float"><b>QAR 18.4B</b> · 94% target</div><div className="chart-labels"><span>Jan</span><span>Mar</span><span>May</span><span>Jun</span></div></div><div className="ask-inline"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Ask Pulse about the enterprise signal"/><button onClick={ask} aria-label="Ask Pulse"><Send size={12}/></button></div>{answer&&<div className="ask-result"><b>Executive answer · </b>{answer}</div>}</section><section className="ref-card metric-card"><div className="card-head"><h2>Gross enterprise value</h2><button className="more">···</button></div><div className="metric-value">QAR 18.4B <span className="delta">↗ 8.2%</span></div><div className="mini-list">{[["Revenue","11.8B",82,""],["EBITDA","3.76B",63,"blue"],["Forecast","18.9B",49,"pink"]].map(row=><div className="mini-row" key={row[0]}><header><span>{row[0]}</span><span>QAR {row[1]}</span></header><div className="mini-track"><i className={String(row[3])} style={{width:`${row[2]}%`}}/></div></div>)}</div></section></div>
      <div className="ref-bottom"><section className="ref-card retention"><div className="card-head"><h2>Performance signal</h2><button className="more">···</button></div><div className="spark-area"><svg viewBox="0 0 260 115" preserveAspectRatio="none"><polyline points="0,87 22,91 44,74 65,77 87,48 108,51 130,40 151,47 173,30 195,58 216,63 238,45 260,52 260,115 0,115"/></svg></div><div className="axis"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div></section><section className="ref-card stat-card"><div className="card-head"><h2>Transactions</h2><button className="more">···</button></div><div className="stat-content"><div><div className="stat-num">106k</div><span className="delta">+34,002 vs last period</span></div><div className="dot-grid">{Array.from({length:30},(_,i)=><i key={i}/>)}</div></div><div className="card-head"><h2>Customers</h2><span className="delta">+320</span></div><div className="stat-content" style={{paddingTop:0}}><div className="stat-num">1,284</div><div className="dot-grid">{Array.from({length:30},(_,i)=><i key={i}/>)}</div></div></section><section className="insight-card"><h3>Pulse insight</h3><strong>94%</strong><p>Enterprise position is ahead of expected pace by 5 points.</p><small>Assets is the clearest watchpoint today.</small></section></div>
    </main></div></div>;
}
export default PulseReference3DDark;