import { useState } from "react";
import { ArrowUpRight, Bell, Bot, ChevronRight, FileText, Home, Inbox, LayoutGrid, Send, Sparkles, Target, UserRound, type LucideIcon } from "lucide-react";
import "./_group.css";

export const groups = [
  ["UCC","5.82B","96%","On track"],["Estithmar","3.46B","101%","Ahead of plan"],["Assets","2.91B","88%","Watch"],["Aura","1.74B","94%","On track"],["PIH","1.38B","97%","On track"],["Baladna","1.62B","111%","Ahead of plan"],["TMT","1.47B","91%","Watch"],
];
export const units = [["UCC Infrastructure","2.42B","98%","On track"],["UCC Contracting","1.87B","95%","On track"],["UCC Hospitality","0.93B","89%","Watch"],["UCC Services","0.60B","103%","Ahead of plan"]];
export function Brand(){return <div className="brand"><span className="brand-mark">P</span><span>pulse.ai</span></div>}
export function Rail({group=false}:{group?:boolean}){const [active,setActive]=useState("Overview");const nav:Array<[LucideIcon,string]>=[[Home,"Overview"],[LayoutGrid,"Businesses"],[Target,"Performance"],[ArrowUpRight,"Forecast"],[Sparkles,"Insights"],[Inbox,"Attention"],[FileText,"Reports"]]; return <aside className="rail"><Brand/><div className="rail-label">{group?"UCC / Group pulse":"Enterprise command"}</div>{nav.map(([Icon,x])=><button key={x} className={active===x?"active":""} onClick={()=>setActive(x)}><Icon size={15}/>{x}</button>)}<div className="rail-bottom">Data refreshed<br/><strong style={{color:"#d3e1d8"}}>Today, 08:42 AST</strong><br/><br/>SSO · Executive access</div></aside>}
export function Header({group=false}:{group?:boolean}){const [period,setPeriod]=useState("YTD");return <header className="topbar"><div><div className="eyebrow">{group?"UCC business pulse":"Enterprise command center"} · Tuesday, 18 June 2024</div><h1 className="serif">{group?"Good morning, Aisha":"Good morning, Mr. Jasim"}</h1><div className="subtle">{group?"A clear view of UCC, its companies and what needs a decision.":"Here is the pulse of your business today."}</div></div><div className="controls"><Bell size={17} color="#6d7c7d"/>{["MTD","QTD","YTD"].map(x=><button className={"control "+(period===x?"active":"")} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}<button className="control">18 Jun 2024</button><span className="avatar">{group?"AN":"JJ"}</span></div></header>}
export function AskPulse(){const [query,setQuery]=useState("");const [answer,setAnswer]=useState("");const ask=()=>{if(query.trim())setAnswer(`Pulse found the clearest signal: Assets is QAR 214M below its YTD forecast, driven by hospitality occupancy (−4.2%) and delayed commercial leasing. I recommend reviewing the July recovery plan before the next steering committee.`)};return <section className="ask"><div className="ask-title"><Bot size={20}/><strong>Ask Pulse</strong></div><p>Ask anything about your business. Pulse returns the answer, the evidence and what to do next.</p><div className="ask-form"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Why is Assets revenue below forecast this month?"/><button onClick={ask} aria-label="Ask Pulse"><Send size={15}/></button></div><div className="suggestions"><button onClick={()=>setQuery("Which business requires my attention today?")}>Which business needs attention?</button><button onClick={()=>setQuery("Give me the 5 things I should know today.")}>Five things I should know</button><button onClick={()=>setQuery("Compare Baladna revenue against budget.")}>Compare against budget</button></div>{answer&&<div className="answer"><strong>Executive answer</strong><br/>{answer}<small>Sources: FY24 forecast model · Hospitality operating report · 17 Jun 2024</small></div>}</section>}
export function Attention({group=false}:{group?:boolean}){const [done,setDone]=useState(false);return <section className="attention"><h3>Needs your attention <span className="mono" style={{color:"#a96863",fontSize:11}}> {done?"3":"4"} items</span></h3>{!done&&<div className="attn"><i className="dot"/><div><div className="attn-title">{group?"UCC Infrastructure":"Budget approval"} · QAR {group?"42M":"42M"}</div><div className="attn-copy">{group?"Capital release awaiting your review.":"Awaiting your approval for infrastructure release."}</div></div><button onClick={()=>setDone(true)}>Review</button></div>}<div className="attn"><i className="dot rose"/><div><div className="attn-title">{group?"Hospitality occupancy":"Assets forecast risk"}</div><div className="attn-copy">{group?"Projected 4.2% below seasonal plan.":"Projected revenue is 7.2% below annual target."}</div></div><button>Analyse</button></div><div className="attn"><i className="dot"/><div><div className="attn-title">{group?"New contract wins":"Estithmar CapEx request"}</div><div className="attn-copy">QAR {group?"18M":"18.4M"} · decision due this week.</div></div><button>Open</button></div></section>}
export function Groups({group=false}:{group?:boolean}){const data=group?units:groups;const [selected,setSelected]=useState(0);return <><div className="section-head"><h2>{group?"UCC companies & business units":"Business groups"}</h2><span>{group?"4 operating areas":"7 groups · consolidated view"} · Select to drill in</span></div><div className="groups">{data.map((g,i)=><button className={"group "+(selected===i?"selected":"")} key={g[0]} onClick={()=>setSelected(i)}><div className="group-name">{g[0]}</div><div className="group-value">QAR {g[1]}</div><div className="group-meta">{g[2]} of target</div><div className={"status "+(g[3].includes("Watch")?"watch":"")}>{g[3]}</div></button>)}</div></>}
export function KPI({group=false}:{group?:boolean}){return <><div className="section-head"><h2>{group?"UCC at a glance":"Enterprise at a glance"}</h2><span>YTD through 18 June · 71% of year elapsed</span></div><div className="kpis"><div className="kpi"><div className="kpi-label">Revenue</div><div className="kpi-value">QAR {group?"5.82B":"18.4B"}</div><div className="kpi-note"><span className="up">↑ {group?"7.4":"8.2"}%</span> vs last year · {group?"96":"94"}% target</div></div><div className="kpi"><div className="kpi-label">EBITDA</div><div className="kpi-value">QAR {group?"1.08":"3.76"}B</div><div className="kpi-note"><span className="up">↑ 6.9%</span> margin {group?"18.6":"20.4"}%</div></div><div className="kpi"><div className="kpi-label">Forecast</div><div className="kpi-value">{group?"97.2":"98.1"}%</div><div className="kpi-note"><span className="up">QAR {group?"5.99":"18.9"}B</span> expected</div></div><div className="kpi"><div className="kpi-label">Time vs achieved</div><div className="kpi-value">{group?"+2":"+5"}%</div><div className="kpi-note">ahead of expected pace</div></div></div></>}
export function Lower({group=false}:{group?:boolean}){return <div className="lower"><section className="panel"><h3>Pulse insight</h3><div className="insight"><strong>{group?"UCC is holding ahead of plan, but Hospitality is narrowing the lead.":"Assets is the clearest enterprise risk this morning."}</strong><p>{group?"Infrastructure and Contracting offset a 4.2% occupancy dip. Recovering the July pipeline protects Q3 pace.":"Revenue is QAR 214M below forecast. Hospitality occupancy and commercial leasing account for 81% of the gap."}</p><div className="bar"><i style={{width:group?"68%":"81%"}}/></div></div></section><section className="panel"><h3>Recent business documents</h3>{["Monthly performance report","Board briefing · June","Forecast review"].map((x,i)=><div className="doc" key={x}><div><strong>{x}</strong><small>{group?"UCC":"Enterprise"} · {i+2} hours ago</small></div><button>View <ChevronRight size={12} style={{verticalAlign:"middle"}}/></button></div>)}</section></div>}
export function BottomNav(){const items:Array<[LucideIcon,string]>=[[Home,"Home"],[LayoutGrid,"Businesses"],[Bot,"Ask Pulse"],[Inbox,"Attention"],[UserRound,"Profile"]];return <nav className="bottom-nav">{items.map(([I,x],i)=><button className={i===0?"active":""} key={x} onClick={()=>{}}><I size={16}/>{x}</button>)}</nav>}