import { useState } from "react";
import { Bell, Search, Send, SlidersHorizontal } from "lucide-react";
import "./PulseReference3D.css";

const businesses = [
  ["UCC", "5.82B", 78, "96% target"], ["Estithmar", "3.46B", 67, "101% target"], ["Assets", "2.91B", 54, "88% target"],
  ["Aura", "1.74B", 46, "94% target"], ["PIH", "1.38B", 39, "97% target"], ["Baladna", "1.62B", 59, "111% target"], ["TMT", "1.47B", 42, "91% target"],
];

export function PulseReference3DLight() {
  const [nav, setNav] = useState("Overview");
  const [period, setPeriod] = useState("YTD");
  const [selected, setSelected] = useState(2);
  const [ask, setAsk] = useState("");
  const [answer, setAnswer] = useState("");
  const [profile, setProfile] = useState(false);
  const [toast, setToast] = useState("");
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  const submit = () => { if (ask.trim()) setAnswer(`Assets is QAR 214M below its ${period} forecast. Hospitality occupancy and commercial leasing account for 81% of the gap.`); };
  return <div className="pulse-ref3d light">
    <div className="ref-window">
      <header className="ref-top"><div className="ref-logo"><img src="/__mockup/images/pulse-ai-official.png" alt="Pulse.ai" /></div><nav className="ref-nav">{["Overview", "Businesses", "Performance", "Forecast", "Insights", "Attention", "Reports"].map(item => <button className={nav === item ? "active" : ""} onClick={() => { setNav(item); notify(`${item} view selected`); }} key={item}>{item}</button>)}</nav><div className="ref-actions"><button className="round-btn" onClick={() => notify("No new notifications")} aria-label="Notifications"><Bell size={14}/></button><button className="ref-avatar" onClick={() => setProfile(!profile)} aria-label="Open account">JJ</button></div></header>
      {profile && <div className="profile-pop"><strong>Mr. Jasim</strong><span>President · Enterprise access</span><button onClick={() => notify("Preferences opened")}>Profile &amp; preferences</button><button onClick={() => notify("Notifications opened")}>Notification settings</button><button onClick={() => setProfile(false)}>Close account menu</button></div>}
      <main className="ref-body"><div className="ref-heading"><div><h1>{nav === "Overview" ? "Overview" : nav}</h1><p>Enterprise command center · Tuesday, 18 June 2024 · Consolidated view</p></div><div className="ref-controls">{["MTD", "QTD", "YTD"].map(item => <button className={`ref-control ${period === item ? "primary" : ""}`} onClick={() => setPeriod(item)} key={item}>{item}</button>)}<button className="ref-control" onClick={() => notify("Date range opened")}>01 Jan – 31 Jul⌄</button><button className="ref-control" onClick={() => notify("Widget added")}><SlidersHorizontal size={11}/> Add widget +</button></div></div>
        <div className="ref-layout"><section className="ref-card"><div className="card-head"><h2>Enterprise revenue</h2><button className="more" onClick={() => notify("Revenue options opened")}>···</button></div><div className="pulse-chart"><div className="chart-grid"><i/><i/><i/><i/><i/></div><div className="bars">{[64,57,73,48,40,35,46,58,52,69,62,78].map((height, i) => <button key={i} className={`bar ${i === selected ? "focus" : ""}`} style={{height: `${height}%`}} onClick={() => { setSelected(i % businesses.length); notify(`Period ${i + 1} selected`); }} aria-label={`Period ${i + 1}`}/>)}</div><div className="chart-float"><b>QAR 18.4B</b> · 94% target</div><div className="chart-labels"><span>Jan</span><span>Mar</span><span>May</span><span>Jun</span></div></div><div className="ask-inline"><Search size={13}/><input value={ask} onChange={e => setAsk(e.target.value)} onKeyDown={e => e.key === "Enter" && submit()} placeholder="What would you like to explore next?" /><button onClick={submit} aria-label="Ask Pulse"><Send size={12}/></button></div>{answer && <div className="ask-result"><b>Ask Pulse · </b>{answer}</div>}</section>
          <section className="ref-card metric-card"><div className="card-head"><h2>Gross enterprise value</h2><button className="more" onClick={() => notify("Value options opened")}>···</button></div><div className="metric-value">QAR 18.4B <span className="delta">↗ 8.2%</span></div><div className="mini-list">{[["Revenue", "11.8B", 82, ""], ["EBITDA", "3.76B", 63, "blue"], ["Forecast", "18.9B", 49, "pink"]].map(row => <div className="mini-row" key={row[0]}><header><span>{row[0]}</span><span>QAR {row[1]}</span></header><div className="mini-track"><i className={String(row[3])} style={{width:`${row[2]}%`}}/></div></div>)}</div></section></div>
        <div className="ref-bottom"><section className="ref-card retention"><div className="card-head"><h2>Performance signal</h2><button className="more" onClick={() => notify("Signal options opened")}>···</button></div><div className="spark-area"><svg viewBox="0 0 260 115" preserveAspectRatio="none"><polyline points="0,87 22,91 44,74 65,77 87,48 108,51 130,40 151,47 173,30 195,58 216,63 238,45 260,52 260,115 0,115"/></svg></div><div className="axis"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div></section><section className="ref-card stat-card"><div className="card-head"><h2>Transactions</h2><button className="more" onClick={() => notify("Transactions opened")}>···</button></div><div className="stat-content"><div><div className="stat-num">106k</div><span className="delta">+34,002 vs last period</span></div><div className="dot-grid">{Array.from({length:30},(_,i)=><i key={i}/>)}</div></div><div className="card-head"><h2>Customers</h2><span className="delta">+320</span></div><div className="stat-content" style={{paddingTop:0}}><div className="stat-num">1,284</div><div className="dot-grid">{Array.from({length:30},(_,i)=><i key={i}/>)}</div></div></section><section className="insight-card"><h3>Pulse insight</h3><strong>94%</strong><p>Enterprise position is ahead of expected pace by 5 points.</p><small>Assets is the clearest watchpoint today.</small></section></div>
        <section className="ref-card" style={{marginTop:10}}><div className="card-head"><h2>Business groups</h2><span style={{fontSize:9,color:"var(--muted)"}}>Select a group to inspect evidence</span></div><div className="mini-list" style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",paddingBottom:12}}>{businesses.map((b,i)=><button key={b[0]} onClick={()=>setSelected(i)} style={{border:0,borderTop:i===selected?"2px solid var(--blue)":"2px solid transparent",background:"transparent",textAlign:"left",padding:"9px 5px",color:"var(--ink)",cursor:"pointer"}}><b style={{fontSize:10}}>{b[0]}</b><strong style={{display:"block",fontSize:12,marginTop:8}}>QAR {b[1]}</strong><small style={{fontSize:8,color:"var(--muted)"}}>{b[3]}</small></button>)}</div></section>
      </main>
    </div>{toast && <div className="toast">{toast}</div>}
  </div>;
}
export default PulseReference3DLight;